export const FETCH_ITEMS = "FETCH_ITEMS";
export const FETCHED_ITEMS = "FETCHED_ITEMS";
export const FETCHING_ITEMS_FAILED = "FETCHING_ITEMS_FAILED";

export const SELECT_ITEM = "SELECT_ITEM";

export const ADD_ITEM = "ADD_ITEM";

export const SELECT_QTY = "SELECT_QTY";

export const CALCULATE_NET_AMOUNT = "CALCULATE_NET_AMOUNT";